---
Name: 'seoextensions'
---

# Include required CSS and JS
LeftAndMain:
  extra_requirements_css:
    - liveseo/css/seo.css
  extra_requirements_javascript:
    - liveseo/javascript/seo.js

SiteTree:
  extensions:
    - 'SeoSiteTreeExtension'
SiteConfig:
  extensions:
    - 'SeoSiteConfigExtension'

# optimize some other modules
GoogleSitemap:
  google_notification_enabled: true
  
# Example of how to exclude extra page types from showing the SEO tab:
# SeoSiteTreeExtension:
#   excluded_page_types:
#     - 'SomePage'
